### ISSUE TITLE
No video image from Camera Ranger 2C

### ISSUE THREAD

**Issue by Nicosdem31** [Imou-OpenPlatform/Imou-Home-Assistant#8]
Integration for Imou Ranger 2C is failing and not giving any video livre stream

_LOGGER.warning(msg, stack_info=True)
2024-12-20 14:38:29.911 DEBUG (MainThread) [custom_components.imou_life] [Camera Bureau] Adding Camera (HD)
2024-12-20 14:38:29.911 DEBUG (MainThread) [custom_components.imou_life] [Camera Bureau] Adding Camera (SD)
2024-12-20 14:38:29.911 DEBUG (MainThread) [custom_components.imou_life] [Camera Bureau] requested camera stream url
2024-12-20 14:38:30.051 DEBUG (MainThread) [custom_components.imou_life] Camera Bureau Callback url added to HA
2024-12-20 14:38:30.067 DEBUG (MainThread) [custom_components.imou_life] Camera Bureau Motion Alarm added to HA
2024-12-20 14:38:30.080 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.camera_bureau_camera for domain camera with platform imou_life
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
await coro
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish
await self.async_internal_added_to_hass()
File "/usr/src/homeassistant/homeassistant/components/camera/init.py", line 829, in async_internal_added_to_hass
await self.async_refresh_providers(write_state=False)
File "/usr/src/homeassistant/homeassistant/components/camera/init.py", line 847, in async_refresh_providers
new_provider = await self._async_get_supported_webrtc_provider(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
async_get_supported_provider
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
^
File "/usr/src/homeassistant/homeassistant/components/camera/init.py", line 871, in _async_get_supported_webrtc_provider
return await fn(self.hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/camera/webrtc.py", line 373, in async_get_supported_provider
if not providers or not (stream_source := await camera.stream_source()):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/imou_life/camera.py", line 106, in stream_source
return await self.sensor_instance.async_get_stream_url()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/site-packages/imouapi/device_entity.py", line 690, in async_get_stream_url
raise APIError(f"unable to get live streaming, url not found in {existing_stream}")
imouapi.exceptions.APIError: unable to get live streaming, url not found in {'url': None, 'token': None}
2024-12-20 14:38:30.082 DEBUG (MainThread) [custom_components.imou_life] [Camera Bureau] requested camera stream url
2024-12-20 14:38:30.097 DEBUG (MainThread) [custom_components.imou_life] Camera Bureau Status added to HA
2024-12-20 14:38:30.100 DEBUG (MainThread) [custom_components.imou_life] Camera Bureau Status indicator added to HA
2024-12-20 14:38:30.192 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.camera_bureau_camerasd for domain camera with platform imou_life
Traceback (most recent call last):

**Comment by Imou-OpenPlatform** [comment]
Hello, may I ask if your current issue has been resolved? Based on the error message you provided, I have not found the corresponding code location. Please update to the latest code and try again. If there are still error messages, please provide relevant device information and we will investigate.

**Comment by Nicosdem31** [comment]
Hello, the issue is still present and the code provided is from the log in my Home Assistant

**Comment by Imou-OpenPlatform** [comment]
> Hello, the issue is still present and the code provided is from the log in my Home Assistant

Please install version v1.0.0 through HACS and try again. If there are any issues, please provide the device serial number for us to troubleshoot.

**Comment by ArunasuraFR** [comment]
Dear @Imou-OpenPlatform,

I'm unable to open a new issue. I had the same issue with but i'm using an imou Cell Go camera.

Here is the error returned in the web console : 

`{
    "code": "start_stream_failed",
    "message": "get_stream_url failed"
}`

Here's the logs : 

`2025-01-16 11:28:28.985 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.fronthouse_1_camera for domain camera with platform imou_life
Traceback (most recent call last):
  File "/config/custom_components/imou_life/camera.py", line 48, in stream_source
    return await self.coordinator.device_manager.async_get_device_stream(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._device
        ^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyimouapi/ha_device.py", line 175, in async_get_device_stream
    raise RequestFailedException("get_stream_url failed")
pyimouapi.exceptions.RequestFailedException: get_stream_url failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 817, in async_internal_added_to_hass
    await self.async_refresh_providers(write_state=False)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 835, in async_refresh_providers
    new_provider = await self._async_get_supported_webrtc_provider(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        async_get_supported_provider
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 859, in _async_get_supported_webrtc_provider
    return await fn(self.hass, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/webrtc.py", line 373, in async_get_supported_provider
    if not providers or not (stream_source := await camera.stream_source()):
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/imou_life/camera.py", line 52, in stream_source
    raise HomeAssistantError(e.message)  # noqa: B904
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant.exceptions.HomeAssistantError: get_stream_url failed
2025-01-16 11:28:53.716 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: get_stream_url failed
`

Already tried the ver. 1.0.0 and 1.0.1 available thru HACS, still the same problem.

**Comment by Imou-OpenPlatform** [comment]
> Dear [@Imou-OpenPlatform](https://github.com/Imou-OpenPlatform),
> 
> I'm unable to open a new issue. I had the same issue with but i'm using an imou Cell Go camera.
> 
> Here is the error returned in the web console :
> 
> `{ "code": "start_stream_failed", "message": "get_stream_url failed" }`
> 
> Here's the logs :
> 
> `2025-01-16 11:28:28.985 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.fronthouse_1_camera for domain camera with platform imou_life Traceback (most recent call last): File "/config/custom_components/imou_life/camera.py", line 48, in stream_source return await self.coordinator.device_manager.async_get_device_stream( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ self._device ^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/site-packages/pyimouapi/ha_device.py", line 175, in async_get_device_stream raise RequestFailedException("get_stream_url failed") pyimouapi.exceptions.RequestFailedException: get_stream_url failed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities await coro File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity await entity.add_to_platform_finish() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish await self.async_internal_added_to_hass() File "/usr/src/homeassistant/homeassistant/components/camera/**init**.py", line 817, in async_internal_added_to_hass await self.async_refresh_providers(write_state=False) File "/usr/src/homeassistant/homeassistant/components/camera/**init**.py", line 835, in async_refresh_providers new_provider = await self._async_get_supported_webrtc_provider( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ async_get_supported_provider ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/src/homeassistant/homeassistant/components/camera/**init**.py", line 859, in _async_get_supported_webrtc_provider return await fn(self.hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/camera/webrtc.py", line 373, in async_get_supported_provider if not providers or not (stream_source := await camera.stream_source()): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/imou_life/camera.py", line 52, in stream_source raise HomeAssistantError(e.message) # noqa: B904 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ homeassistant.exceptions.HomeAssistantError: get_stream_url failed 2025-01-16 11:28:53.716 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: get_stream_url failed `
> 
> Already tried the ver. 1.0.0 and 1.0.1 available thru HACS, still the same problem.

Hello, can you provide logs of calling the imou open API? It seems that the interface call failed

**Comment by ArunasuraFR** [comment]
> > Dear [@Imou-OpenPlatform](https://github.com/Imou-OpenPlatform),
> > I'm unable to open a new issue. I had the same issue with but i'm using an imou Cell Go camera.
> > Here is the error returned in the web console :
> > `{ "code": "start_stream_failed", "message": "get_stream_url failed" }`
> > Here's the logs :
> > `2025-01-16 11:28:28.985 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.fronthouse_1_camera for domain camera with platform imou_life Traceback (most recent call last): File "/config/custom_components/imou_life/camera.py", line 48, in stream_source return await self.coordinator.device_manager.async_get_device_stream( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ self._device ^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/site-packages/pyimouapi/ha_device.py", line 175, in async_get_device_stream raise RequestFailedException("get_stream_url failed") pyimouapi.exceptions.RequestFailedException: get_stream_url failed
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities await coro File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity await entity.add_to_platform_finish() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish await self.async_internal_added_to_hass() File "/usr/src/homeassistant/homeassistant/components/camera/**init**.py", line 817, in async_internal_added_to_hass await self.async_refresh_providers(write_state=False) File "/usr/src/homeassistant/homeassistant/components/camera/**init**.py", line 835, in async_refresh_providers new_provider = await self._async_get_supported_webrtc_provider( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ async_get_supported_provider ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/src/homeassistant/homeassistant/components/camera/**init**.py", line 859, in _async_get_supported_webrtc_provider return await fn(self.hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/camera/webrtc.py", line 373, in async_get_supported_provider if not providers or not (stream_source := await camera.stream_source()): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/imou_life/camera.py", line 52, in stream_source raise HomeAssistantError(e.message) # noqa: B904 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ homeassistant.exceptions.HomeAssistantError: get_stream_url failed 2025-01-16 11:28:53.716 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: get_stream_url failed `
> > Already tried the ver. 1.0.0 and 1.0.1 available thru HACS, still the same problem.
> 
> Hello, can you provide logs of calling the imou open API? It seems that the interface call failed

Dear team,

The only log available from Home Assistant is : 

`Enregistreur: aiohttp.server
Source: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451
S'est produit pour la première fois: 11:16:49 (4 occurrences)
Dernier enregistrement: 11:27:20

Error handling request
Traceback (most recent call last):
  File "/config/custom_components/imou_life/camera.py", line 60, in async_camera_image
    return await self.coordinator.device_manager.async_get_device_image(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._device
        ^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyimouapi/ha_device.py", line 198, in async_get_device_image
    data = await self.device_manager.async_get_device_snap(device.device_id, device.channel_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyimouapi/device.py", line 244, in async_get_device_snap
    return await self._imouApiClient.async_request_api(API_ENDPOINT_SET_DEVICE_SNAP, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyimouapi/openapi.py", line 82, in async_request_api
    raise RequestFailedException(msg)
pyimouapi.exceptions.RequestFailedException: DV1010:Snapshot too frequent, please try again later. `

Another option seem to be working (Flash, Work light etc...). But no preview / live stream.

**Comment by Nicosdem31** [comment]
Hello, 

Is there any answer from the dev team ? 

Thanks a lot

**Comment by ArunasuraFR** [comment]
> Hello,
> 
> Is there any answer from the dev team ?
> 
> Thanks a lot

Hi @Nicosdem31 !

No news, still not working with this plugin.

Depends on the kind of camera, you can get the camera's RTSP stream on Home Assistant to get a preview/live stream without the imou integration.

My Ranger 2C work perfectly with RTSP stream, but my Cell Go Full Color not (battery camera, no extra stream, no rtsp on).

RTSP url for Ranger 2C camera : 

`rtsp://admin:YOUR_CAMERA_PASSWORD_HERE@YOUR_CAMERA_IP_HERE:554/cam/realmonitor?channel=1&subtype=0`

**Comment by Imou-OpenPlatform** [comment]
Hello, a new integrated version has been released, please try after updating.

**Comment by farberm** [comment]
Same problem here with my Ranger - no streaming feed.


Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:676
integration: Camera ([documentation](https://www.home-assistant.io/integrations/camera), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+camera%22))
First occurred: 1:28:39 PM (2 occurrences)
Last logged: 1:28:39 PM

Error adding entity camera.mema_camera_camera for domain camera with platform imou_life
Error adding entity camera.mema_camera_camerasd for domain camera with platform imou_life
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 676, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1377, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 690, in async_internal_added_to_hass
    await self.async_refresh_providers(write_state=False)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 704, in async_refresh_providers
    new_provider = await self._async_get_supported_webrtc_provider(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        async_get_supported_provider
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 721, in _async_get_supported_webrtc_provider
    return await fn(self.hass, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/webrtc.py", line 362, in async_get_supported_provider
    if not providers or not (stream_source := await camera.stream_source()):
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/imou_life/camera.py", line 107, in stream_source
    return await self.sensor_instance.async_get_stream_url()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/imouapi/device_entity.py", line 690, in async_get_stream_url
    raise APIError(f"unable to get live streaming, url not found in {existing_stream}")
imouapi.exceptions.APIError: unable to get live streaming, url not found in {'url': None, 'token': None}

**Comment by Imou-OpenPlatform** [comment]
Thanks for reporting this. To debug stream/still issues we need: **Home Assistant version**, **integration version**, **exact camera model**, **device serial number (S/N)**, whether you installed via **HACS zip** or manual copy, reproduction steps, and **log excerpts** mentioning `imou_life`, `get_stream_url`, or `camera` (ERROR/DEBUG). Without that, we cannot tell whether it is stream URL, codec, go2rtc, or a model-specific API response.
